---
- name: "Check variables: mandatory variables"
  ansible.builtin.fail:
    msg: "Variable '{{ item[1] }}' for host '{{ item[0] }}' is not defined"
  when: hostvars[item[0]][item[1]] is not defined
  loop: |
    {{
      groups['arouteserver_managed_routeservers'] |
      product([
        arouteserver_varname_rs_asn,
        arouteserver_varname_daemon,
        arouteserver_varname_daemon_version,
        arouteserver_varname_router_id,
        arouteserver_varname_local_networks
      ]) |
      list
    }}
  tags:
    - always

- name: "Check variables: clients source"
  ansible.builtin.fail:
    msg: >
      At least one variable among arouteserver_clients_cfg_file,
      arouteserver_clients_from_euroix_file and arouteserver_clients_from_euroix_url
      must be set
  when: >
    (arouteserver_clients_cfg_file is not defined or not arouteserver_clients_cfg_file) and
    (arouteserver_clients_from_euroix_file is not defined or not arouteserver_clients_from_euroix_file) and
    (arouteserver_clients_from_euroix_url is not defined or not arouteserver_clients_from_euroix_url)
  tags:
    - always

- name: "Check variables: ixp_id is set when arouteserver_clients_from_euroix_* is used"
  ansible.builtin.fail:
    msg: "When arouteserver_clients_from_euroix_* is used, arouteserver_clients_from_euroix_ixp_id must be set"
  when: >
    (arouteserver_clients_from_euroix_ixp_id is not defined or not arouteserver_clients_from_euroix_ixp_id) and
    (
      (arouteserver_clients_from_euroix_file is defined and arouteserver_clients_from_euroix_file) or
      (arouteserver_clients_from_euroix_url is defined and arouteserver_clients_from_euroix_url)
    )
  tags:
    - always

- name: "Be sure var dir exists"
  ansible.builtin.file:
    path: "{{ arouteserver_var }}"
    state: directory
    mode: ug=rwx,o=rx
  changed_when: false
  tags:
    - always

- name: "Check if build_rs_config is present"
  ansible.builtin.command: "true"
  register: build_rs_config_tag_is_not_present
  changed_when: false

- name: "Install bgpq4"
  ansible.builtin.include_tasks: bgpq4.yml

- name: "Install ARouteServer"
  ansible.builtin.include_tasks: installation.yml

- name: "Configure general policy (general.yml file)"
  ansible.builtin.include_tasks: configure_general_policy.yml
  with_items:
    - "{{ groups['arouteserver_managed_routeservers'] }}"
  loop_control:
    loop_var: rs_hostname
  tags:
    - configure_policy

- name: "Configure client list (clients.yml file)"
  ansible.builtin.include_tasks: configure_client_list.yml
  tags:
    - configure_clients

- name: "Rebuild rs config on build_rs_config tag"
  ansible.builtin.include_tasks: build_rs_config.yml
  when: build_rs_configs_tag_is_not_present is not defined
  with_items:
    - "{{ groups['arouteserver_managed_routeservers'] }}"
  loop_control:
    loop_var: rs_hostname
  tags:
    - build_rs_config
