---
- name: "Request reconfiguration of general policies"
  listen: "arouteserver: reconfigure general policies"
  ansible.builtin.include_tasks: configure_general_policy.yml
  with_items: "{{ groups['arouteserver_managed_routeservers'] }}"
  loop_control:
    loop_var: rs_hostname

- name: "Request rebuilding of rs configs"
  listen: "arouteserver: rebuild rs config files"
  ansible.builtin.include_tasks: build_rs_config.yml
  with_items: "{{ groups['arouteserver_managed_routeservers'] }}"
  loop_control:
    loop_var: rs_hostname
